// app/layout.tsx
import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack"; // Import stackServerApp here
import Providers from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StackProvider app={stackServerApp}>
          <StackTheme>
            <Providers>{children}</Providers>{" "}
            {/* Pass children into Providers */}
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
